### ISSUE TITLE
Implement the Scoring System

### ISSUE THREAD

**Issue by Janfiderheld** [Janfiderheld/Snake-That-MO#6]
- find a way to show the score
- save the score locally
- discuss what should give points

**Comment by Janfiderheld** [comment]
Score is shown (Implementation of the HUD)

**Comment by NiclasMuss** [comment]
Score can now be changed as a variable. Is increased by collecting Coins. Coins can have different Values

**Comment by Janfiderheld** [comment]
@NiclasMuss added the possibility to save the highscore in a file.
Now that feature is in an extra class
